# Generated by Django 4.1.1 on 2022-10-15 17:27

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areaofwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('image', models.ImageField(null=True, upload_to=projects.models.generate_filename)),
                ('date', models.DateTimeField(null=True)),
                ('areaofwork', models.ManyToManyField(to='areaofwork.areaofwork')),
            ],
        ),
    ]
