# Generated by Django 4.1.1 on 2022-10-16 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
