# Generated by Django 4.1.1 on 2022-10-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaofwork', '0001_initial'),
        ('projects', '0002_alter_projects_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='areaofwork',
            field=models.ManyToManyField(related_name='projects', to='areaofwork.areaofwork'),
        ),
    ]
