# Generated by Django 4.1.1 on 2022-10-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_areaofwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='featured',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
