# Generated by Django 4.1.1 on 2022-10-16 05:23

import campaign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_projects_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('image', models.ImageField(null=True, upload_to=campaign.models.generate_filename)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ManyToManyField(to='projects.projects')),
            ],
        ),
    ]
