# Generated by Django 4.1.1 on 2022-10-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigns',
            old_name='project',
            new_name='projects',
        ),
    ]
