# Generated by Django 4.1.1 on 2022-10-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_date'),
        ('campaign', '0002_rename_project_campaigns_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='projects',
            field=models.ManyToManyField(related_name='campaigns', to='projects.projects'),
        ),
    ]
