# Generated by Django 4.1.1 on 2022-10-17 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='project',
        ),
    ]
