# Generated by Django 4.1.1 on 2023-01-18 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_alter_campaigns_organized_by'),
        ('gallery', '0003_remove_gallery_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='campaign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='campaign.campaigns'),
        ),
    ]
